Unit tests refactoring
codex-team/hawk.workers.go pull request #15
Opened 2022-08-24 08:28 UTC by nikmel2803

2022-08-24 08:36 UTC, n0str commented on lib/broker/broker.go
> +		false,
please, comment this

2022-08-24 09:17 UTC, n0str approved these changes

2022-08-24 10:56 UTC, thomasfire requested changes

2022-08-24 10:56 UTC, thomasfire commented on go.work.sum
> +github.com/stretchr/objx v0.4.0/go.mod h1:YvHI0jy2hoMjB+UWwv71VJQ9isScKT/TqJzVSSt89Yw=
Seems like a packet manager cache

2022-08-24 10:56 UTC, thomasfire commented on lib/broker/go.sum
> +github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
same cache-like

2022-08-24 10:56 UTC, thomasfire commented on lib/worker/go.sum
> +github.com/benbjohnson/clock v1.1.0 h1:Q92kusRqC1XV2MjkWETPvjJVqKetz1OzxZB7mHJLju8=
same cache

2022-08-24 10:56 UTC, thomasfire commented on lib/worker/worker.go
> +func CreateTestLogger() *zap.SugaredLogger {
doubt it should be in the lib part

2022-08-24 10:56 UTC, thomasfire commented on mocks/task_handler.go
> +	ret := _m.Called(ctx)
wtf

2022-08-25 04:17 UTC, thomasfire approved these changes
ничего не понятно, но очень интересно

2022-08-25 04:23 UTC, merged